### ISSUE TITLE
No such file or directory: 'checkpoints\\model_dict.pth'

### ISSUE THREAD

**Issue by naive2kj90** [Usman-Rafique/gaf#1]
I am trying to run code with a pre-trained model as written in Evaluation & Visualization section.
However, when I run visualize.py for eval_trained.py, an error message pop up saying there is no such file as 'model_dict.pth'

it seems like a pre-trained file, Is there any way I can run this code?

I used
cfg.model.name = 'GAF'
on config.py file.

**Comment by Usman-Rafique** [comment]
Hi. Thank you for pointing this. The pre-trained model for GAF was not added in this repository.

This has been resolved in #92a3e2ac13ff2579467d6ff81b24a2ad5ab54940. 

I have added the pre-trained model. I have also updated the evaluation and visualization files. Please update your local repository with current master and everything should be fine.

**Comment by Usman-Rafique** [comment]
Hi. Thanks for pointing out. The trained model for GAF was not included in the repository. 

This issue has been resolved in https://github.com/Usman-Rafique/gaf/commit/92a3e2ac13ff2579467d6ff81b24a2ad5ab54940

I have updated training and evaluation scripts to work with the model `'GAF'` as well. Please update your local repo from master.

**Comment by Usman-Rafique** [comment]
resolved in https://github.com/Usman-Rafique/gaf/commit/92a3e2ac13ff2579467d6ff81b24a2ad5ab54940
